[theme]
base = "dark"
primaryColor = "#8b5cf6"
backgroundColor = "#0f1420"
secondaryBackgroundColor = "#141a2a"
textColor = "#ffffff"

[server]
enableXsrfProtection = true
cookieSecret = "findocgpt-pro-theme"

[general]
email = ""

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E40AF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1F2937"
